import type {
  ExplorerModel,
  ExplorerPreview,
  ExplorerSource,
  QueryMockMatch,
} from "@/lib/explorer/types"

const previews: ExplorerPreview[] = [
  {
    id: "pg.public.customers",
    sourceType: "postgresql",
    sourceLabel: "warehouse-prod",
    kind: "table",
    label: "Customer master",
    path: ["warehouse-prod", "public", "customers"],
    name: "customers",
    rowLabel: "rows",
    rowCount: 12486,
    summary: "Primary customer dimension with lifecycle, segment, and commercial health fields.",
    columns: [
      { name: "customer_id", type: "uuid", nullable: false, sample: "cst_1042" },
      { name: "company_name", type: "text", nullable: false, sample: "Northstar Foods" },
      { name: "segment", type: "text", nullable: false, sample: "Enterprise" },
      { name: "region", type: "text", nullable: false, sample: "EMEA" },
      { name: "lifetime_value", type: "numeric", nullable: false, sample: "184500" },
      { name: "health_tier", type: "text", nullable: false, sample: "watch" },
      { name: "updated_at", type: "timestamp", nullable: false, sample: "2026-04-10 16:22:03" },
    ],
    rows: [
      {
        customer_id: "cst_1042",
        company_name: "Northstar Foods",
        segment: "Enterprise",
        region: "EMEA",
        lifetime_value: 184500,
        health_tier: "watch",
        updated_at: "2026-04-10 16:22",
      },
      {
        customer_id: "cst_1188",
        company_name: "Lattice Freight",
        segment: "Mid-market",
        region: "North America",
        lifetime_value: 132400,
        health_tier: "healthy",
        updated_at: "2026-04-10 15:08",
      },
      {
        customer_id: "cst_1219",
        company_name: "Harbor Retail",
        segment: "SMB",
        region: "APAC",
        lifetime_value: 48200,
        health_tier: "expansion",
        updated_at: "2026-04-10 11:47",
      },
      {
        customer_id: "cst_1321",
        company_name: "Aster Health",
        segment: "Enterprise",
        region: "North America",
        lifetime_value: 211300,
        health_tier: "healthy",
        updated_at: "2026-04-10 09:31",
      },
      {
        customer_id: "cst_1403",
        company_name: "Pine Signal",
        segment: "Mid-market",
        region: "LATAM",
        lifetime_value: 90600,
        health_tier: "watch",
        updated_at: "2026-04-09 19:15",
      },
    ],
  },
  {
    id: "pg.public.orders",
    sourceType: "postgresql",
    sourceLabel: "warehouse-prod",
    kind: "table",
    label: "Order pipeline",
    path: ["warehouse-prod", "public", "orders"],
    name: "orders",
    rowLabel: "rows",
    rowCount: 89321,
    summary: "Transactional orders table for fulfillment, order value, and current status analysis.",
    columns: [
      { name: "order_id", type: "bigint", nullable: false, sample: "5001842" },
      { name: "customer_id", type: "uuid", nullable: false, sample: "cst_1042" },
      { name: "order_total", type: "numeric", nullable: false, sample: "8240.50" },
      { name: "status", type: "text", nullable: false, sample: "shipped" },
      { name: "channel", type: "text", nullable: false, sample: "direct" },
      { name: "created_at", type: "timestamp", nullable: false, sample: "2026-04-08 10:02:00" },
    ],
    rows: [
      { order_id: 5001842, customer_id: "cst_1042", order_total: 8240.5, status: "shipped", channel: "direct", created_at: "2026-04-08 10:02" },
      { order_id: 5001843, customer_id: "cst_1188", order_total: 2490.75, status: "processing", channel: "partner", created_at: "2026-04-08 10:07" },
      { order_id: 5001844, customer_id: "cst_1321", order_total: 14520, status: "allocated", channel: "direct", created_at: "2026-04-08 10:12" },
      { order_id: 5001845, customer_id: "cst_1219", order_total: 690, status: "cancelled", channel: "self-serve", created_at: "2026-04-08 10:18" },
      { order_id: 5001846, customer_id: "cst_1403", order_total: 1930.25, status: "processing", channel: "partner", created_at: "2026-04-08 10:24" },
    ],
  },
  {
    id: "pg.finance.invoices",
    sourceType: "postgresql",
    sourceLabel: "warehouse-prod",
    kind: "table",
    label: "Collections ledger",
    path: ["warehouse-prod", "finance", "invoices"],
    name: "invoices",
    rowLabel: "rows",
    rowCount: 18437,
    summary: "Finance ledger with invoice amounts, due dates, and payment risk state.",
    columns: [
      { name: "invoice_id", type: "text", nullable: false, sample: "inv_40018" },
      { name: "account_name", type: "text", nullable: false, sample: "Aster Health" },
      { name: "amount_due", type: "numeric", nullable: false, sample: "12800" },
      { name: "days_overdue", type: "integer", nullable: false, sample: "14" },
      { name: "owner", type: "text", nullable: false, sample: "collections-west" },
      { name: "status", type: "text", nullable: false, sample: "overdue" },
    ],
    rows: [
      { invoice_id: "inv_40018", account_name: "Aster Health", amount_due: 12800, days_overdue: 14, owner: "collections-west", status: "overdue" },
      { invoice_id: "inv_40019", account_name: "Northstar Foods", amount_due: 9100, days_overdue: 3, owner: "collections-emea", status: "at_risk" },
      { invoice_id: "inv_40020", account_name: "Harbor Retail", amount_due: 2400, days_overdue: 0, owner: "collections-apac", status: "open" },
      { invoice_id: "inv_40021", account_name: "Pine Signal", amount_due: 5400, days_overdue: 21, owner: "collections-latam", status: "overdue" },
      { invoice_id: "inv_40022", account_name: "Lattice Freight", amount_due: 7800, days_overdue: 7, owner: "collections-na", status: "pending" },
    ],
  },
  {
    id: "mongo.crm.accounts",
    sourceType: "mongodb",
    sourceLabel: "context-cluster",
    kind: "collection",
    label: "CRM account snapshots",
    path: ["context-cluster", "crm", "accounts"],
    name: "accounts",
    rowLabel: "documents",
    rowCount: 5321,
    summary: "Account-level context with owner, renewal posture, and relationship notes flattened for browsing.",
    columns: [
      { name: "_id", type: "objectId", nullable: false, sample: "661743c8ab12d84ef1001ca2" },
      { name: "account_name", type: "string", nullable: false, sample: "Northstar Foods" },
      { name: "renewal_risk", type: "string", nullable: false, sample: "medium" },
      { name: "owner", type: "string", nullable: false, sample: "Maya Chen" },
      { name: "health_note", type: "string", nullable: true, sample: "Expansion delayed pending Q3 budget reset" },
      { name: "last_touch_days", type: "number", nullable: false, sample: "9" },
    ],
    rows: [
      { _id: "661743c8ab12d84ef1001ca2", account_name: "Northstar Foods", renewal_risk: "medium", owner: "Maya Chen", health_note: "Expansion delayed pending Q3 budget reset", last_touch_days: 9 },
      { _id: "661743c8ab12d84ef1001ca3", account_name: "Lattice Freight", renewal_risk: "low", owner: "Jules Patel", health_note: "Executive sponsor joined the last review", last_touch_days: 4 },
      { _id: "661743c8ab12d84ef1001ca4", account_name: "Aster Health", renewal_risk: "high", owner: "Rhea Singh", health_note: "Open support escalations affecting upsell motion", last_touch_days: 12 },
      { _id: "661743c8ab12d84ef1001ca5", account_name: "Harbor Retail", renewal_risk: "low", owner: "Mina Park", health_note: "Seasonal volume expected to rebound next month", last_touch_days: 6 },
      { _id: "661743c8ab12d84ef1001ca6", account_name: "Pine Signal", renewal_risk: "medium", owner: "Noah Diaz", health_note: "Discount request still under finance review", last_touch_days: 15 },
    ],
  },
  {
    id: "mongo.crm.activities",
    sourceType: "mongodb",
    sourceLabel: "context-cluster",
    kind: "collection",
    label: "Activity feed",
    path: ["context-cluster", "crm", "activities"],
    name: "activities",
    rowLabel: "documents",
    rowCount: 90443,
    summary: "Recent customer-facing touchpoints, categorized for operator review and pipeline triage.",
    columns: [
      { name: "_id", type: "objectId", nullable: false, sample: "661743c8ab12d84ef1004dd1" },
      { name: "account_name", type: "string", nullable: false, sample: "Aster Health" },
      { name: "activity_type", type: "string", nullable: false, sample: "call" },
      { name: "owner", type: "string", nullable: false, sample: "Rhea Singh" },
      { name: "sentiment", type: "string", nullable: false, sample: "at-risk" },
      { name: "created_at", type: "date", nullable: false, sample: "2026-04-10T09:18:00Z" },
    ],
    rows: [
      { _id: "661743c8ab12d84ef1004dd1", account_name: "Aster Health", activity_type: "call", owner: "Rhea Singh", sentiment: "at-risk", created_at: "2026-04-10T09:18Z" },
      { _id: "661743c8ab12d84ef1004dd2", account_name: "Northstar Foods", activity_type: "email", owner: "Maya Chen", sentiment: "neutral", created_at: "2026-04-10T08:55Z" },
      { _id: "661743c8ab12d84ef1004dd3", account_name: "Pine Signal", activity_type: "meeting", owner: "Noah Diaz", sentiment: "positive", created_at: "2026-04-09T18:12Z" },
      { _id: "661743c8ab12d84ef1004dd4", account_name: "Lattice Freight", activity_type: "note", owner: "Jules Patel", sentiment: "positive", created_at: "2026-04-09T16:21Z" },
      { _id: "661743c8ab12d84ef1004dd5", account_name: "Harbor Retail", activity_type: "email", owner: "Mina Park", sentiment: "neutral", created_at: "2026-04-09T14:02Z" },
    ],
  },
  {
    id: "mongo.events.page_views",
    sourceType: "mongodb",
    sourceLabel: "context-cluster",
    kind: "collection",
    label: "Product engagement events",
    path: ["context-cluster", "events", "page_views"],
    name: "page_views",
    rowLabel: "documents",
    rowCount: 231918,
    summary: "Behavioral event stream rolled into a clean collection preview for product and GTM analysis.",
    columns: [
      { name: "_id", type: "objectId", nullable: false, sample: "661743c8ab12d84ef1008bf1" },
      { name: "account_name", type: "string", nullable: false, sample: "Northstar Foods" },
      { name: "page", type: "string", nullable: false, sample: "/usage/forecast" },
      { name: "visitor_role", type: "string", nullable: false, sample: "admin" },
      { name: "session_minutes", type: "number", nullable: false, sample: "18" },
      { name: "viewed_at", type: "date", nullable: false, sample: "2026-04-10T07:10:00Z" },
    ],
    rows: [
      { _id: "661743c8ab12d84ef1008bf1", account_name: "Northstar Foods", page: "/usage/forecast", visitor_role: "admin", session_minutes: 18, viewed_at: "2026-04-10T07:10Z" },
      { _id: "661743c8ab12d84ef1008bf2", account_name: "Aster Health", page: "/billing/credits", visitor_role: "finance", session_minutes: 9, viewed_at: "2026-04-10T07:42Z" },
      { _id: "661743c8ab12d84ef1008bf3", account_name: "Lattice Freight", page: "/api/keys", visitor_role: "developer", session_minutes: 12, viewed_at: "2026-04-10T08:01Z" },
      { _id: "661743c8ab12d84ef1008bf4", account_name: "Harbor Retail", page: "/reports/cohorts", visitor_role: "analyst", session_minutes: 16, viewed_at: "2026-04-10T08:14Z" },
      { _id: "661743c8ab12d84ef1008bf5", account_name: "Pine Signal", page: "/settings/team", visitor_role: "admin", session_minutes: 5, viewed_at: "2026-04-10T08:19Z" },
    ],
  },
  {
    id: "query.customer_ltv_rollup",
    sourceType: "postgresql",
    sourceLabel: "SQL workbench",
    kind: "query",
    label: "Customer LTV result",
    path: ["workbench", "saved-results", "customer_ltv_rollup"],
    name: "customer_ltv_rollup",
    rowLabel: "rows",
    rowCount: 8,
    summary: "Mock result set for ranking customers by lifetime value and segment health.",
    queryHint: "Matched canned result from SQL workbench query.",
    columns: [
      { name: "customer_id", type: "uuid", nullable: false, sample: "cst_1321" },
      { name: "company_name", type: "text", nullable: false, sample: "Aster Health" },
      { name: "segment", type: "text", nullable: false, sample: "Enterprise" },
      { name: "lifetime_value", type: "numeric", nullable: false, sample: "211300" },
      { name: "health_tier", type: "text", nullable: false, sample: "healthy" },
    ],
    rows: [
      { customer_id: "cst_1321", company_name: "Aster Health", segment: "Enterprise", lifetime_value: 211300, health_tier: "healthy" },
      { customer_id: "cst_1042", company_name: "Northstar Foods", segment: "Enterprise", lifetime_value: 184500, health_tier: "watch" },
      { customer_id: "cst_1188", company_name: "Lattice Freight", segment: "Mid-market", lifetime_value: 132400, health_tier: "healthy" },
      { customer_id: "cst_1403", company_name: "Pine Signal", segment: "Mid-market", lifetime_value: 90600, health_tier: "watch" },
      { customer_id: "cst_1219", company_name: "Harbor Retail", segment: "SMB", lifetime_value: 48200, health_tier: "expansion" },
    ],
  },
  {
    id: "query.order_status_rollup",
    sourceType: "postgresql",
    sourceLabel: "SQL workbench",
    kind: "query",
    label: "Order status rollup",
    path: ["workbench", "saved-results", "order_status_rollup"],
    name: "order_status_rollup",
    rowLabel: "rows",
    rowCount: 4,
    summary: "Mock result set summarizing order pipeline state by status.",
    queryHint: "Matched canned result from SQL workbench query.",
    columns: [
      { name: "status", type: "text", nullable: false, sample: "processing" },
      { name: "order_count", type: "integer", nullable: false, sample: "284" },
      { name: "gross_value", type: "numeric", nullable: false, sample: "182440.25" },
    ],
    rows: [
      { status: "processing", order_count: 284, gross_value: 182440.25 },
      { status: "allocated", order_count: 121, gross_value: 94120.0 },
      { status: "shipped", order_count: 910, gross_value: 582930.5 },
      { status: "cancelled", order_count: 36, gross_value: 12980.75 },
    ],
  },
  {
    id: "query.overdue_invoices",
    sourceType: "postgresql",
    sourceLabel: "SQL workbench",
    kind: "query",
    label: "Overdue invoice queue",
    path: ["workbench", "saved-results", "overdue_invoices"],
    name: "overdue_invoices",
    rowLabel: "rows",
    rowCount: 5,
    summary: "Mock result set highlighting overdue invoices ordered by exposure.",
    queryHint: "Matched canned result from SQL workbench query.",
    columns: [
      { name: "invoice_id", type: "text", nullable: false, sample: "inv_40021" },
      { name: "account_name", type: "text", nullable: false, sample: "Pine Signal" },
      { name: "amount_due", type: "numeric", nullable: false, sample: "5400" },
      { name: "days_overdue", type: "integer", nullable: false, sample: "21" },
      { name: "status", type: "text", nullable: false, sample: "overdue" },
    ],
    rows: [
      { invoice_id: "inv_40018", account_name: "Aster Health", amount_due: 12800, days_overdue: 14, status: "overdue" },
      { invoice_id: "inv_40019", account_name: "Northstar Foods", amount_due: 9100, days_overdue: 3, status: "at_risk" },
      { invoice_id: "inv_40022", account_name: "Lattice Freight", amount_due: 7800, days_overdue: 7, status: "pending" },
      { invoice_id: "inv_40021", account_name: "Pine Signal", amount_due: 5400, days_overdue: 21, status: "overdue" },
      { invoice_id: "inv_40020", account_name: "Harbor Retail", amount_due: 2400, days_overdue: 0, status: "open" },
    ],
  },
]

const queryMocks: QueryMockMatch[] = [
  {
    id: "mock-customer-ltv",
    label: "Customer value ranking",
    description: "Ranks customers by lifetime value and health tier.",
    previewId: "query.customer_ltv_rollup",
    sampleQuery:
      "SELECT customer_id, company_name, segment, lifetime_value, health_tier\nFROM public.customers\nORDER BY lifetime_value DESC\nLIMIT 8;",
    matchers: ["from public.customers", "lifetime_value", "health_tier"],
  },
  {
    id: "mock-order-rollup",
    label: "Order status summary",
    description: "Summarizes the order pipeline by status.",
    previewId: "query.order_status_rollup",
    sampleQuery:
      "SELECT status, COUNT(*) AS order_count, SUM(order_total) AS gross_value\nFROM public.orders\nGROUP BY status\nORDER BY gross_value DESC;",
    matchers: ["from public.orders", "group by status", "sum(order_total)"],
  },
  {
    id: "mock-overdue-invoices",
    label: "Overdue invoice queue",
    description: "Highlights overdue invoices by amount and aging.",
    previewId: "query.overdue_invoices",
    sampleQuery:
      "SELECT invoice_id, account_name, amount_due, days_overdue, status\nFROM finance.invoices\nWHERE days_overdue > 0\nORDER BY amount_due DESC\nLIMIT 10;",
    matchers: ["from finance.invoices", "days_overdue", "amount_due"],
  },
]

const sources: ExplorerSource[] = [
  {
    id: "postgresql",
    type: "postgresql",
    label: "PostgreSQL",
    description: "Relational warehouse with schemas, tables, and SQL-first exploration.",
    status: "live",
    nodes: [
      {
        id: "pg-server",
        kind: "server",
        label: "warehouse-prod",
        meta: "3 schemas",
        defaultExpanded: true,
        children: [
          {
            id: "pg-schema-public",
            kind: "schema",
            label: "public",
            meta: "2 tables",
            defaultExpanded: true,
            children: [
              {
                id: "pg-table-customers",
                kind: "table",
                label: "customers",
                meta: "12.5k rows",
                previewId: "pg.public.customers",
              },
              {
                id: "pg-table-orders",
                kind: "table",
                label: "orders",
                meta: "89.3k rows",
                previewId: "pg.public.orders",
              },
            ],
          },
          {
            id: "pg-schema-finance",
            kind: "schema",
            label: "finance",
            meta: "1 table",
            defaultExpanded: true,
            children: [
              {
                id: "pg-table-invoices",
                kind: "table",
                label: "invoices",
                meta: "18.4k rows",
                previewId: "pg.finance.invoices",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "mongodb",
    type: "mongodb",
    label: "MongoDB",
    description: "Context collections flattened into a neat, operator-friendly browser.",
    status: "mock",
    nodes: [
      {
        id: "mongo-cluster",
        kind: "cluster",
        label: "context-cluster",
        meta: "2 databases",
        defaultExpanded: true,
        children: [
          {
            id: "mongo-db-crm",
            kind: "database",
            label: "crm",
            meta: "2 collections",
            defaultExpanded: true,
            children: [
              {
                id: "mongo-collection-accounts",
                kind: "collection",
                label: "accounts",
                meta: "5.3k docs",
                previewId: "mongo.crm.accounts",
              },
              {
                id: "mongo-collection-activities",
                kind: "collection",
                label: "activities",
                meta: "90.4k docs",
                previewId: "mongo.crm.activities",
              },
            ],
          },
          {
            id: "mongo-db-events",
            kind: "database",
            label: "events",
            meta: "1 collection",
            defaultExpanded: true,
            children: [
              {
                id: "mongo-collection-page-views",
                kind: "collection",
                label: "page_views",
                meta: "231.9k docs",
                previewId: "mongo.events.page_views",
              },
            ],
          },
        ],
      },
    ],
  },
]

export function getExplorerModel(): ExplorerModel {
  return {
    sources,
    previews,
    queryMocks,
    defaultPreviewId: "pg.public.customers",
    initialQuery: queryMocks[0].sampleQuery,
  }
}
